/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRewriteSummaryRouteImport } from './routes/api/rewrite-summary'
import { Route as ApiRewriteSectionRouteImport } from './routes/api/rewrite-section'
import { Route as ApiRecommendJobsRouteImport } from './routes/api/recommend-jobs'
import { Route as ApiJobTipRouteImport } from './routes/api/job-tip'
import { Route as ApiGenerateFromJdRouteImport } from './routes/api/generate-from-jd'

const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewriteSummaryRoute = ApiRewriteSummaryRouteImport.update({
  id: '/api/rewrite-summary',
  path: '/api/rewrite-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRewriteSectionRoute = ApiRewriteSectionRouteImport.update({
  id: '/api/rewrite-section',
  path: '/api/rewrite-section',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendJobsRoute = ApiRecommendJobsRouteImport.update({
  id: '/api/recommend-jobs',
  path: '/api/recommend-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobTipRoute = ApiJobTipRouteImport.update({
  id: '/api/job-tip',
  path: '/api/job-tip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateFromJdRoute = ApiGenerateFromJdRouteImport.update({
  id: '/api/generate-from-jd',
  path: '/api/generate-from-jd',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/api/generate-from-jd': typeof ApiGenerateFromJdRoute
  '/api/job-tip': typeof ApiJobTipRoute
  '/api/recommend-jobs': typeof ApiRecommendJobsRoute
  '/api/rewrite-section': typeof ApiRewriteSectionRoute
  '/api/rewrite-summary': typeof ApiRewriteSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/api/generate-from-jd': typeof ApiGenerateFromJdRoute
  '/api/job-tip': typeof ApiJobTipRoute
  '/api/recommend-jobs': typeof ApiRecommendJobsRoute
  '/api/rewrite-section': typeof ApiRewriteSectionRoute
  '/api/rewrite-summary': typeof ApiRewriteSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/api/generate-from-jd': typeof ApiGenerateFromJdRoute
  '/api/job-tip': typeof ApiJobTipRoute
  '/api/recommend-jobs': typeof ApiRecommendJobsRoute
  '/api/rewrite-section': typeof ApiRewriteSectionRoute
  '/api/rewrite-summary': typeof ApiRewriteSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/api/generate-from-jd'
    | '/api/job-tip'
    | '/api/recommend-jobs'
    | '/api/rewrite-section'
    | '/api/rewrite-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/api/generate-from-jd'
    | '/api/job-tip'
    | '/api/recommend-jobs'
    | '/api/rewrite-section'
    | '/api/rewrite-summary'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/api/generate-from-jd'
    | '/api/job-tip'
    | '/api/recommend-jobs'
    | '/api/rewrite-section'
    | '/api/rewrite-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  ApiGenerateFromJdRoute: typeof ApiGenerateFromJdRoute
  ApiJobTipRoute: typeof ApiJobTipRoute
  ApiRecommendJobsRoute: typeof ApiRecommendJobsRoute
  ApiRewriteSectionRoute: typeof ApiRewriteSectionRoute
  ApiRewriteSummaryRoute: typeof ApiRewriteSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewrite-summary': {
      id: '/api/rewrite-summary'
      path: '/api/rewrite-summary'
      fullPath: '/api/rewrite-summary'
      preLoaderRoute: typeof ApiRewriteSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rewrite-section': {
      id: '/api/rewrite-section'
      path: '/api/rewrite-section'
      fullPath: '/api/rewrite-section'
      preLoaderRoute: typeof ApiRewriteSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommend-jobs': {
      id: '/api/recommend-jobs'
      path: '/api/recommend-jobs'
      fullPath: '/api/recommend-jobs'
      preLoaderRoute: typeof ApiRecommendJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/job-tip': {
      id: '/api/job-tip'
      path: '/api/job-tip'
      fullPath: '/api/job-tip'
      preLoaderRoute: typeof ApiJobTipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-from-jd': {
      id: '/api/generate-from-jd'
      path: '/api/generate-from-jd'
      fullPath: '/api/generate-from-jd'
      preLoaderRoute: typeof ApiGenerateFromJdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  ApiGenerateFromJdRoute: ApiGenerateFromJdRoute,
  ApiJobTipRoute: ApiJobTipRoute,
  ApiRecommendJobsRoute: ApiRecommendJobsRoute,
  ApiRewriteSectionRoute: ApiRewriteSectionRoute,
  ApiRewriteSummaryRoute: ApiRewriteSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
